apiVersion: batch/v1
kind: Job
metadata:
  name: pre-upgrade
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    metadata:
      name: pre-upgrade
    spec:
      restartPolicy: {{ .Values.preUpgrade.restartPolicy }}
      containers:
        - name: pre-upgrade
          image: "{{ .Values.preUpgrade.image.repository }}:{{ .Values.imageTag }}"
          command: ["./pre-upgrade.sh", "{{ .Values.service.name }}"]
