apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: {{ .Values.app.name }}
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.service.sourcePort }}
      targetPort: {{ .Values.service.targetPort }}
